server:
  port: 8762

eureka:
  instance:
    hostname: registry-sr

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/